name: Deploy Push

on:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        image:
          - name: latest
            python_version: "3.12"
          - name: python3.12
            python_version: "3.12"
          - name: python3.11
            python_version: "3.11"
          - name: python3.10
            python_version: "3.10"
          - name: python3.9
            python_version: "3.9"
          - name: python3.8
            python_version: "3.8"
          - name: python3.7
            python_version: "3.7"
          - name: python3.12-slim
            python_version: "3.12"
          - name: python3.11-slim
            python_version: "3.11"
          - name: python3.10-slim
            python_version: "3.10"
          - name: python3.9-slim
            python_version: "3.9"
          - name: python3.8-slim
            python_version: "3.8"
          - name: python3.12-alpine3.19
            python_version: "3.12"
          - name: python3.11-alpine3.19
            python_version: "3.11"
          - name: python3.10-alpine3.19
            python_version: "3.10"
          - name: python3.9-alpine3.19
            python_version: "3.9"
          - name: python3.8-alpine3.19
            python_version: "3.8"
          - name: python3.7-alpine3.18
            python_version: "3.7"
      fail-fast: true
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: "3.9"
      - name: Install Dependencies
        run: python -m pip install docker pytest
      - name: Deploy Image
        run: python scripts/build_push.py
        env:
          NAME: ${{ matrix.image.name }}
          PYTHON_VERSION: ${{ matrix.image.python_version }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
